### ISSUE TITLE
[Question] Access other settings from YAML config file ?

### ISSUE THREAD

**Issue by pdesgarets** [lorenwest/node-config#327]
Hi,
I am using YAML config files. Is there a way I can define a setting once and then reference it in other places ? Something like 
```
settings_group:
  setting: foo
other_group:
  other_setting: # something to reference settings_group.setting
```
Thanks !

Edit : I could do
```
settings_group:
  setting: &settings_group.setting foo
other_group:
  other_setting: *settings_group.setting
```
But then I have to redefine other_group.other_setting every time I redefine settings_group.setting, e.g. for each environment, so this is not ideal.
