### ISSUE TITLE
Wish: Deferred configuration using YAML format

### ISSUE THREAD

**Issue by lee5i3** [lorenwest/node-config#371]
I am using YAML for my configuration, it would be nice to have my configurations reused, even if it was something like this..

```
default:
  service:
    name: "test"
    desc: "${service.name}"
```
