### ISSUE TITLE
Error: hash not properly dedented

### ISSUE THREAD

**Issue by norman784** [lorenwest/node-config#39]
I've got this error, dont know why but since I updated to the lasted (0.4.18) its throwing this error

```
Error: Cannot parse config file: '/path/to/my/app/config/default.yaml': Error: hash not properly dedented, near "f147d1a81b06c7ed8c25512ba"
```

The most strange thing its that it doesnt take the first char of the facebook secret (its a number) and the end of the string. My yaml looks like

``` yaml
Facebook:
  app:
    id:        xxxx
    secret:    xf147d1a81b06c7ed8c25512baxxxx
    scope:     email
```
