### ISSUE TITLE
Problem with ENV VAR substitution on YAML files?

### ISSUE THREAD

**Issue by ScottChapman** [lorenwest/node-config#591]
in version 3.2.5 I am trying to do a pretty simple YAML config with env var substitution, but I am having difficulty making it work.

My default.yaml:
```yaml
---
kafka:
  clientId: 'clientId'
  consumer:
    groupId: groupId
    topics:
      - name: default-topic
        avroEnabled: false
```

and my custom-environment-variables.yaml:
```yaml
---
kafka:
  clientId: 'clientId'
  consumer:
    groupId: groupId
    topics:
      - name: "TOPIC_NAME"
        avroEnabled: false
```

Works fine if I remove the custom env var file, but I get an " Illegal key type for substitution map at kafka.consumer: object" if I try to use it.

What am I missing?
