### ISSUE TITLE
Nested setModuleDefaults overwrites original config values

### ISSUE THREAD

**Issue by TomFrost** [lorenwest/node-config#68]
With the following **default.yaml**:

```
modules:
  login:
    users:
      tom: somePass
      bob: somePass
```

Running this script:

```
var CONFIG = require('config');
var mods = CONFIG.setModuleDefaults('modules', {}),
    login = mods.setModuleDefaults('login', {});
console.log(login.users);
```

sets the 'login' submodule to {} instead of retaining the values defined there.  That last line produces `undefined`.
